name: linting, testing, building
on: 
  push:
    branches: ['master']
  pull_request: 
    branches: ['master']
jobs:
  Pipeline-Production-Project:
    runs-on: windows-10
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build productio project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint
      - name: linting scss
        run: npm run lint-scss
      - name: unit testing
        run: npm run unit
      - name: build storybook
        run: npm run build-storybook
      - name: screenshot testing
        run: npm run loki:ci

