name: linting, testing, building
on: 
  push:
    branches: ['master', 'develop']
  pull_request: 
    branches: ['master', 'develop']
jobs:
  Pipeline-Production-Project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: linting typescript
        run: npm run lint
        if: always()
      - name: linting scss
        run: npm run lint-scss
        if: always()
      - name: unit testing
        run: npm run unit
        if: always()
      - name: build storybook and screenshot testing
        run: npm run build-storybook:ci
      #   if: always()
      # - name: screenshot testing
      #   run: npm run loki:ci

